# Generated by Django 4.1.7 on 2023-09-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_article_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='comment_pictures/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.article')),
                ('user_profile_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofileinfo')),
            ],
        ),
    ]
