# Generated by Django 4.1.7 on 2023-09-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='cover_picture',
            field=models.FileField(blank=True, null=True, upload_to='cover_pictures/'),
        ),
    ]
